#!/usr/bin/env bash
set -e

CWD=$(cd "${0%/*}" && pwd)
LIB=$(cd "${CWD}/../lib" && pwd)
OUT=$(cd "${CWD}/../out" && pwd)

# parse arguments
while [[ "$#" > 0 ]]; do case $1 in
  --scd-only) SCD_ONLY=1;;
  --mcd-only) MCT_ONLY=1;;
esac; shift; done

if [ -z $MCT_ONLY ]; then
  . $CWD/deploy-scd
  deploy_scd
fi

if [ -z $SCD_ONLY ]; then
  . $CWD/deploy-mct
  deploy_mct_dds
fi
