#!/usr/bin/env bash

function jq_inplace {
  TMP=$(mktemp)
  jq "$1" > $TMP && mv $TMP "$2"
}

function sed_inplace {
  # sed's -i argument behaves differently on macOS, hence this hack
  sed -i.bak "$1" $2 && rm $2.bak
}

function deploy_mct_dds {
  DDS=$LIB/tss-deploy-scripts
  cd $DDS

  export MCT_PAUSE_DELAY=1

  TMP=$(mktemp)

  # change deploy-testchain not to send 10000 ETH
  sed_inplace 's/10000 eth/1 eth/' deploy-testchain.sh

  # deploy migration contracts with local tub and gem
  TUB=$(sudo cat $OUT/addresses.json | jq '.TUB')
  GEM=$(sudo cat $OUT/addresses.json | jq '.GEM')
  GOV=$(sudo cat $OUT/addresses.json | jq '.GOV')
  DEPLOY=$DDS/deploy-testchain.json
  sudo cat $DEPLOY | jq_inplace ".migration = $(<$LIB/deploy-migration.json)" $DEPLOY
  sudo cat $DEPLOY | jq_inplace ".migration.tub = $(echo $TUB)" $DEPLOY
  sudo cat $DEPLOY | jq_inplace ".tokens.ETH.gem = $(echo $GEM)" $DEPLOY
  sudo cat $DEPLOY | jq_inplace ".gov = $(echo $GOV)" $DEPLOY

  # change ds-pause delay to non-zero
  sudo cat $DEPLOY | jq_inplace ".pauseDelay = $(echo $MCT_PAUSE_DELAY)" $DEPLOY

  # submodule contracts are deprecated; this nix command
  # installs all necessary dependencies
  IN_NIX_SHELL=yes nix run -f $DDS -c deploy-testchain.sh

  # uncomment below to add more ilks
  # DPA=$LIB/testchain-tss-deployment-scripts/contracts/tss-proxy-actions
  # cd $DPA/lib/tss-cdp-manager/lib/tss-deploy/
  # export DAPP_SOLC_VERSION=0.5.0
  # . bin/deploy-ilk-col1 B
  # . bin/deploy-ilk-eth B

  ls \
    $DDS/out/abi/* \
    $DDS/contracts/tss-deploy/out/*.abi | \
    grep -v -E "(Fab|Dev|Test|Like|t_sol|lib_|src_)" | \
    xargs sh -c "sudo cp \$@ $OUT/mcd" placeholder
  # why the placeholder? see https://en.wikipedia.org/wiki/Xargs#Shell_trick

  # sort addresses alphabetically
  jq -S . $DDS/out/addresses.json > $OUT/addresses-mcd.json

  # all done, go home!
  cd -
}
